### ISSUE TITLE
put "latest" tag to use

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/bioconductor_full#7] opened 2019-10-11 09:41 UTC
Could you use the "latest" tag to refer to the current release version? This would allow automatic updating in certain settings without users having to change e.g. `RELEASE_3_9` to `RELEASE_3_10` after the next release is made.

**Comment by mtmorgan** [comment] 2019-10-11 12:48
For consistency it seems like the tag should be 'release' rather than 'latest', since we talk about  'release' and 'devel' branches and not 'latest' (and also usually the latest updates will be to master...). 

From an error reporting perspective it's not helpful to say 'I'm using the latest version of Bioconductor', so in general (not just in the context of these docker images)I think the project should move to using specific names ('I'm using RELEASE_3_9 of Bioconductor') for each release. Likewise enforcing using of explicit RELEASE_* tags enhances reproducibility.

If we were to go forward with this, the way the repo is set up is that the 'master' branch is 'devel', and then it branches for each release. So the 'release' tag would need to be associated with the RELEASE_3_9 branch, and then transferred to RELEASE_3_10 when that is created. This surprisingly simple task seems like it would trip us up, forgetting to transfer the tag...

The 'release' tag should be in addition to a tag for the named release RELEASE_3_9 etc.

Any thoughts @lwaldron on the comments above?

**Comment by lwaldron** [comment] 2019-10-15 14:17
To me it makes little difference whether it's 'release' or 'latest' - I only suggested 'latest' because Docker uses it as a default when no tag is specified, but 'release' does make sense in Bioconductor's language. I want to create systems to keep machines up to date with a minimum of intervention, and this would help.

**Comment by lshep** [comment] 2019-10-17 11:15
I have added a "release" 
 tag  -  It is right now the RELEASE_3_9 
 and we will add a task to make sure this is updated at release time. 
  https://cloud.docker.com/u/bioconductor/repository/docker/bioconductor/bioconductor_full/tags

**Comment by lshep** [comment] 2019-10-17 11:16
We still also have the RELEASE_3_9 / RELEASE_3_8  and will continue to do also RELEASE_X_Y  to specify releases but will have "devel"/"release" to reflect current

**Closed as completed by lshep** 2019-10-17 11:15 UTC
